// src/pages/Confirmation.vue

<template>
  <div class="min-h-screen flex flex-col">
    <AppHeader showBackButton title="Confirmación" />
    
    <main class="flex-1 container max-w-2xl mx-auto p-6">
      <TransitionWrapper class="space-y-6">
        <WorkflowStep 
          :steps="workflowSteps" 
          currentStepId="confirmation" 
          class="mb-8"
        />
        
        <FormSection 
          title="Resumen de Información" 
          description="Revisa la información proporcionada antes de enviar"
          :icon="ClipboardCheck"
        >
          <div class="space-y-4">
            <div v-if="personalInfo" class="bg-muted/50 rounded-lg p-4 space-y-3">
              <h4 class="text-sm font-medium">Datos Personales</h4>
              <div class="grid grid-cols-2 gap-2 text-xs">
                <div><span class="font-medium">Nombre:</span> {{ personalInfo.fullName }}</div>
                <div><span class="font-medium">DNI/NIE:</span> {{ personalInfo.dni }}</div>
                <div><span class="font-medium">Email:</span> {{ personalInfo.email }}</div>
                <div><span class="font-medium">Teléfono:</span> {{ personalInfo.phone }}</div>
              </div>
              
              <h4 class="text-sm font-medium pt-2">Dirección</h4>
              <div class="grid grid-cols-2 gap-2 text-xs">
                <div><span class="font-medium">Dirección:</span> {{ personalInfo.address }}</div>
                <div><span class="font-medium">Código Postal:</span> {{ personalInfo.postalCode }}</div>
                <div><span class="font-medium">Ciudad:</span> {{ personalInfo.city }}</div>
                <div><span class="font-medium">Provincia:</span> {{ personalInfo.province }}</div>
              </div>
              
              <h4 class="text-sm font-medium pt-2">Datos Bancarios</h4>
              <div class="grid grid-cols-2 gap-2 text-xs">
                <div><span class="font-medium">IBAN:</span> {{ personalInfo.iban }}</div>
                <div><span class="font-medium">Titular:</span> {{ personalInfo.accountHolder }}</div>
              </div>
            </div>
            
            <div v-if="documentInfo" class="bg-muted/50 rounded-lg p-4">
              <h4 class="text-sm font-medium mb-2">Documentos Subidos</h4>
              <div class="space-y-2 text-xs">
                <div v-if="documentInfo.idCard && documentInfo.idCard.length">
                  <span class="font-medium">DNI/NIE:</span> {{ documentInfo.idCard.join(', ') }}
                </div>
                <div v-if="documentInfo.socialSecurity && documentInfo.socialSecurity.length">
                  <span class="font-medium">Tarjeta Seg. Social:</span> {{ documentInfo.socialSecurity.join(', ') }}
                </div>
                <div v-if="documentInfo.bankCertificate && documentInfo.bankCertificate.length">
                  <span class="font-medium">Certificado Bancario:</span> {{ documentInfo.bankCertificate.join(', ') }}
                </div>
              </div>
            </div>
            
            <div v-if="documentsInfo" class="bg-muted/50 rounded-lg p-4">
              <h4 class="text-sm font-medium mb-2">Documentos Firmados</h4>
              <div class="space-y-2 text-xs">
                <div>
                  <span class="font-medium">Recibo Entrega Uniforme:</span> 
                  {{ documentsInfo.signatures.uniformReceipt ? 'Firmado ✓' : 'No firmado ✗' }}
                </div>
                <div>
                  <span class="font-medium">Acuse Recibo Información Preventiva:</span> 
                  {{ documentsInfo.signatures.safetyInfo ? 'Firmado ✓' : 'No firmado ✗' }}
                </div>
                <div v-if="documentsInfo.safetyExam">
                  <span class="font-medium">Examen Prevención:</span> 
                  {{ documentsInfo.safetyExam.score.toFixed(0) }}% 
                  ({{ documentsInfo.safetyExam.passed ? 'Aprobado ✓' : 'No aprobado ✗' }})
                </div>
              </div>
            </div>
            
            <div class="space-y-3 pt-2">
              <div class="flex items-center space-x-2">
                <input
                  type="checkbox"
                  id="confirmCheck"
                  v-model="confirmCheck"
                  class="h-4 w-4 rounded border-gray-300 text-primary focus:ring-primary"
                />
                <label for="confirmCheck" class="text-sm font-medium">
                  Confirmo que toda la información proporcionada es correcta
                </label>
              </div>
              
              <div class="flex items-center space-x-2">
                <input
                  type="checkbox"
                  id="privacyCheck"
                  v-model="privacyCheck"
                  class="h-4 w-4 rounded border-gray-300 text-primary focus:ring-primary"
                />
                <label for="privacyCheck" class="text-sm font-medium">
                  He leído y acepto la política de privacidad y protección de datos
                </label>
              </div>
              
              <p v-if="errors.confirm" class="text-xs text-destructive">{{ errors.confirm }}</p>
            </div>
          </div>
        </FormSection>
        
        <div class="flex justify-end pt-4">
          <Button 
            @click="handleSubmit"
            :isLoading="isSubmitting"
            icon="SendHorizontal"
            iconPosition="right"
          >
            Enviar Información
          </Button>
        </div>
      </TransitionWrapper>
    </main>
    
    <AppFooter />
  </div>
</template>

<script>
import AppHeader from '../components/layout/Header.vue';
import AppFooter from '../components/layout/Footer.vue';
import Button from '../components/ui/Button.vue';
import TransitionWrapper from '../components/ui/TransitionWrapper.vue';
import WorkflowStep from '../components/workflow/WorkflowStep.vue';
import FormSection from '../components/workflow/FormSection.vue';
import { ClipboardCheck, SendHorizontal } from 'lucide-vue-next';

export default {
  name: 'Confirmation',
  components: {
    AppHeader,
    AppFooter,
    Button,
    TransitionWrapper,
    WorkflowStep,
    FormSection,
    ClipboardCheck,
    SendHorizontal
  },
  data() {
    return {
      workflowSteps: [
        { id: 'personal-info', title: 'Información Personal' },
        { id: 'documents-upload', title: 'Subir Documentos' },
        { id: 'sign-documents', title: 'Firmar Documentos' },
        { id: 'confirmation', title: 'Confirmación' }
      ],
      personalInfo: null,
      documentInfo: null,
      documentsInfo: null,
      confirmCheck: false,
      privacyCheck: false,
      errors: {},
      isSubmitting: false
    }
  },
  mounted() {
    // Load saved data
    try {
      const personalInfo = localStorage.getItem('personalInfo');
      if (personalInfo) {
        this.personalInfo = JSON.parse(personalInfo);
      }
      
      const documentInfo = localStorage.getItem('documentInfo');
      if (documentInfo) {
        this.documentInfo = JSON.parse(documentInfo);
      }
      
      const documentsInfo = localStorage.getItem('documentsInfo');
      if (documentsInfo) {
        this.documentsInfo = JSON.parse(documentsInfo);
      }
    } catch (e) {
      console.error('Error loading saved data', e);
    }
  },
  methods: {
    validateForm() {
      const errors = {};
      
      if (!this.confirmCheck || !this.privacyCheck) {
        errors.confirm = 'Es necesario aceptar ambas confirmaciones para continuar';
      }
      
      this.errors = errors;
      return Object.keys(errors).length === 0;
    },
    
    handleSubmit() {
      if (!this.validateForm()) {
        return;
      }
      
      this.isSubmitting = true;
      
      // Simulate API call
      setTimeout(() => {
        // In a real app, here you would send all collected data to your backend
        
        // Save completion status
        localStorage.setItem('processCompleted', 'true');
        
        this.isSubmitting = false;
        this.$router.push('/completed');
      }, 2000);
    }
  }
}
</script>

// src/pages/Confirmation.tsx

import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import Button from '@/components/ui-custom/Button';
import TransitionWrapper from '@/components/ui-custom/TransitionWrapper';
import WorkflowStep, { Step } from '@/components/workflow/WorkflowStep';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui-custom/Card';
import { CheckCircle, User, File, FileSignature, Send, ArrowLeft } from 'lucide-react';
import { toast } from 'sonner';

const workflowSteps: Step[] = [
  { id: 'personal-info', title: 'Información Personal' },
  { id: 'documents-upload', title: 'Subir Documentos' },
  { id: 'sign-documents', title: 'Firmar Documentos' },
  { id: 'confirmation', title: 'Confirmación' }
];

const Confirmation = () => {
  const navigate = useNavigate();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isCompleted, setIsCompleted] = useState(false);
  
  // In a real app, you would fetch this data from your backend
  // For this demo, we'll retrieve from localStorage
  const personalInfo = JSON.parse(localStorage.getItem('personalInfo') || '{}');
  const documentInfo = JSON.parse(localStorage.getItem('documentInfo') || '{}');
  const documentsInfo = JSON.parse(localStorage.getItem('documentsInfo') || '{}');
  
  const handleSubmit = () => {
    setIsSubmitting(true);
    
    // Simulate API call
    setTimeout(() => {
      // Clear localStorage after successful submission
      localStorage.removeItem('personalInfo');
      localStorage.removeItem('documentInfo');
      localStorage.removeItem('documentsInfo');
      
      setIsSubmitting(false);
      setIsCompleted(true);
      
      toast.success('Todos los documentos han sido enviados correctamente');
    }, 2000);
  };
  
  return (
    <div className="min-h-screen flex flex-col">
      <Header showBackButton title="Confirmación" />
      
      <main className="flex-1 container max-w-2xl mx-auto p-6">
        <TransitionWrapper className="space-y-6">
          <WorkflowStep 
            steps={workflowSteps} 
            currentStepId="confirmation" 
            className="mb-8"
          />
          
          {isCompleted ? (
            <div className="text-center py-12 space-y-6 animate-scale-in">
              <div className="inline-flex items-center justify-center rounded-full bg-primary/10 p-6">
                <CheckCircle className="h-12 w-12 text-primary" />
              </div>
              
              <h2 className="text-2xl font-semibold">¡Proceso Completado!</h2>
              
              <p className="text-muted-foreground max-w-md mx-auto">
                Todos tus documentos han sido enviados correctamente. Recibirás un email de confirmación en breve.
              </p>
              
              <Button 
                onClick={() => navigate('/')}
                className="mt-6"
                icon={<ArrowLeft size={16} />}
                iconPosition="left"
              >
                Volver al inicio
              </Button>
            </div>
          ) : (
            <div className="space-y-6">
              <Card variant="glass">
                <CardHeader>
                  <CardTitle>Resumen de la Documentación</CardTitle>
                  <CardDescription>
                    Revisa la información antes de enviar
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-3">
                    <div className="flex items-center gap-2">
                      <User size={18} className="text-primary" />
                      <h3 className="text-sm font-medium">Información Personal</h3>
                    </div>
                    
                    {Object.keys(personalInfo).length > 0 ? (
                      <div className="grid grid-cols-2 gap-2 text-sm bg-muted/30 p-3 rounded-md">
                        <div>
                          <p className="text-muted-foreground">Nombre:</p>
                          <p className="font-medium">{personalInfo.firstName} {personalInfo.lastName}</p>
                        </div>
                        <div>
                          <p className="text-muted-foreground">DNI/NIE:</p>
                          <p className="font-medium">{personalInfo.idNumber}</p>
                        </div>
                        <div>
                          <p className="text-muted-foreground">Email:</p>
                          <p className="font-medium">{personalInfo.email}</p>
                        </div>
                        <div>
                          <p className="text-muted-foreground">Teléfono:</p>
                          <p className="font-medium">{personalInfo.phone}</p>
                        </div>
                      </div>
                    ) : (
                      <p className="text-sm text-muted-foreground">No se ha completado la información personal</p>
                    )}
                  </div>
                  
                  <div className="space-y-3">
                    <div className="flex items-center gap-2">
                      <File size={18} className="text-primary" />
                      <h3 className="text-sm font-medium">Documentos Subidos</h3>
                    </div>
                    
                    {Object.keys(documentInfo).length > 0 ? (
                      <div className="text-sm bg-muted/30 p-3 rounded-md space-y-2">
                        <div>
                          <p className="text-muted-foreground">DNI/NIE:</p>
                          <p className="font-medium">
                            {documentInfo.idCard && documentInfo.idCard.length > 0 
                              ? `${documentInfo.idCard.length} archivo(s)` 
                              : 'No subido'}
                          </p>
                        </div>
                        <div>
                          <p className="text-muted-foreground">Seguridad Social:</p>
                          <p className="font-medium">
                            {documentInfo.socialSecurity && documentInfo.socialSecurity.length > 0 
                              ? `${documentInfo.socialSecurity.length} archivo(s)` 
                              : 'No subido'}
                          </p>
                        </div>
                        <div>
                          <p className="text-muted-foreground">Certificado Bancario:</p>
                          <p className="font-medium">
                            {documentInfo.bankCertificate && documentInfo.bankCertificate.length > 0 
                              ? `${documentInfo.bankCertificate.length} archivo(s)` 
                              : 'No subido'}
                          </p>
                        </div>
                      </div>
                    ) : (
                      <p className="text-sm text-muted-foreground">No se han subido documentos</p>
                    )}
                  </div>
                  
                  <div className="space-y-3">
                    <div className="flex items-center gap-2">
                      <FileSignature size={18} className="text-primary" />
                      <h3 className="text-sm font-medium">Documentos Firmados</h3>
                    </div>
                    
                    {documentsInfo && documentsInfo.signatures ? (
                      <div className="text-sm bg-muted/30 p-3 rounded-md space-y-2">
                        <div>
                          <p className="text-muted-foreground">Recibo Entrega Uniforme:</p>
                          <p className="font-medium">
                            {documentsInfo.signatures.uniformReceipt ? 'Firmado' : 'No firmado'}
                          </p>
                        </div>
                        <div>
                          <p className="text-muted-foreground">Información Preventiva:</p>
                          <p className="font-medium">
                            {documentsInfo.signatures.safetyInfo ? 'Firmado' : 'No firmado'}
                          </p>
                        </div>
                        
                        {documentsInfo.safetyExam && documentsInfo.safetyExam.score !== undefined && (
                          <div>
                            <p className="text-muted-foreground">Examen Prevención:</p>
                            <p className="font-medium">
                              Completado - Puntuación: {documentsInfo.safetyExam.score}% 
                              ({documentsInfo.safetyExam.passed ? 'Aprobado' : 'No aprobado'})
                            </p>
                          </div>
                        )}
                      </div>
                    ) : (
                      <p className="text-sm text-muted-foreground">No se han firmado documentos</p>
                    )}
                  </div>
                </CardContent>
              </Card>
              
              <div className="bg-primary/5 rounded-xl p-6 border border-primary/20">
                <h3 className="text-base font-medium mb-2">Aviso de Privacidad</h3>
                <p className="text-sm text-muted-foreground mb-4">
                  Al enviar estos documentos, confirmas que toda la información proporcionada es correcta y aceptas 
                  el procesamiento de tus datos personales de acuerdo con nuestra política de privacidad.
                </p>
                
                <Button 
                  onClick={handleSubmit}
                  isLoading={isSubmitting}
                  icon={<Send size={16} />}
                  fullWidth
                >
                  Enviar toda la documentación
                </Button>
              </div>
            </div>
          )}
        </TransitionWrapper>
      </main>
      
      <Footer />
    </div>
  );
};

export default Confirmation;
