// src/pages/ProcessCompleted.tsx

import React from "react";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";
import { Link } from "react-router-dom";

const ProcessCompleted = () => {
  return (
    <div className="min-h-screen flex flex-col items-center justify-center p-6 text-center">
      <div className="max-w-md w-full space-y-8 animate-scale-in">
        <div className="bg-green-100 rounded-full p-3 w-16 h-16 flex items-center justify-center mx-auto">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="h-8 w-8 text-green-600"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M5 13l4 4L19 7"
            />
          </svg>
        </div>
        
        <h1 className="text-3xl font-bold">¡Proceso Completado!</h1>
        <p className="text-muted-foreground">
          Toda la información ha sido procesada correctamente. Recibirá un correo electrónico con la confirmación y próximos pasos.
        </p>
        
        <div className="pt-4">
          <Link to="/">
            <Button variant="outline" className="gap-2">
              <ArrowLeft className="h-4 w-4" />
              Volver al inicio
            </Button>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default ProcessCompleted;

// src/pages/ProcessCompleted.vue

<template>
  <div class="min-h-screen flex flex-col">
    <AppHeader title="Proceso Completado" />
    
    <main class="flex-1 container max-w-2xl mx-auto p-6 flex flex-col items-center justify-center">
      <TransitionWrapper class="text-center">
        <div class="inline-flex h-24 w-24 items-center justify-center rounded-full bg-primary/20 mb-6">
          <div class="h-12 w-12 text-primary flex items-center justify-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check-circle">
              <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/>
              <polyline points="22 4 12 14.01 9 11.01"/>
            </svg>
          </div>
        </div>
        
        <h1 class="text-3xl font-bold mb-4">¡Información Enviada!</h1>
        
        <p class="text-muted-foreground mb-8 max-w-md mx-auto">
          Se ha completado el proceso de envío de documentación. Hemos enviado una copia al correo electrónico proporcionado.
        </p>
        
        <div class="p-4 rounded-lg bg-muted/50 mb-8 max-w-md mx-auto">
          <h3 class="font-medium text-base mb-2">Próximos pasos</h3>
          <p class="text-sm text-muted-foreground">
            El departamento de Recursos Humanos revisará la documentación y se pondrá en contacto con usted en los próximos días.
          </p>
        </div>
        
        <Button 
          @click="goToStart"
          variant="outline"
        >
          Volver al inicio
        </Button>
      </TransitionWrapper>
    </main>
    
    <AppFooter />
  </div>
</template>

<script>
import AppHeader from '../components/layout/Header.vue';
import AppFooter from '../components/layout/Footer.vue';
import Button from '../components/ui/Button.vue';
import TransitionWrapper from '../components/ui/TransitionWrapper.vue';

export default {
  name: 'ProcessCompleted',
  components: {
    AppHeader,
    AppFooter,
    Button,
    TransitionWrapper
  },
  methods: {
    goToStart() {
      this.$router.push('/');
    }
  }
}
</script>
